### ISSUE TITLE
Channel Selection

### ISSUE THREAD

**Issue by brunocalado** [piecesofcodecom/soundscape-adventure#11]
Hi. Can you add a setting to define which channel the soundscapes will play? Music, Environment
![image](https://github.com/user-attachments/assets/1887c059-e87f-46aa-8df5-94aaefb162ea)

**Comment by brunocalado** [comment]
Manual setting don't work

**Comment by mrcomac** [comment]
You can select the channel from the sidebar pannel

https://github.com/user-attachments/assets/f12c694c-3b08-4980-be39-a9a93caa93ef

**Comment by LarryBoi** [comment]
> You can select the channel from the sidebar pannel
> Gravando.2024-08-11.120842.mp4

As of the latest version, this doesn't work for me at all. All my soundscapes play in the Music channel, even though I have selected 'Environment' in the playlist edit menu. The same occurs after a restart, and affects new sounds as well as ones added after I changed the playlist channel.
