### ISSUE TITLE
Suggestion - rework soundscape folder scanning

### ISSUE THREAD

**Issue by LarryBoi** [piecesofcodecom/soundscape-adventure#16]
When scanning for folders to put potential soundscapes in, the add-on suggests subfolders of soundscape folders as possible places to put soundscapes in. This is unintuitive behaviour - I would suggest that the add-on only scan for possible soundscape folders one layer into the folder in which soundscapes are stored. Here is a screenshot of the behaviour as it currently is:

![Subfolder](https://github.com/user-attachments/assets/46ac4f57-05af-417a-8c9d-ffb99142dde1)

Folder structure of above example:
`Soundscapes Folder`
`---Soundscape-Underground`
`------Ambience`
`------Loop`
`------Random`

In the above example, only 'Soundscape_Underground' should be shown as an option. Additionally, it would be useful for the add-on to inform you if the folder you wish to use as a soundscape has an invalid folder structure. For example, I accidentally named my 'Ambience' folder 'Ambient', and had to double check the spelling when I realised none of my ambient sounds were showing.

**Comment by mrcomac** [comment]
This should be fixed in V0.1.2

**Comment by LarryBoi** [comment]
> This should be fixed in V0.1.2

Everything seems to work! Being informed of required missing folders is a very helpful feature, thanks for implementing it. I found a new bug with folder scanning, but I opened a new issue for it: #19

**Comment by mrcomac** [comment]
thank you @LarryBoi for that report.
