### ISSUE TITLE
Small CSS Improvement

### ISSUE THREAD

**Issue by brunocalado** [piecesofcodecom/soundscape-adventure#6]
I want to suggest a small fix to the CSS.

- Make the buttons read better when selected
- Increase the size of the title of the sound 
- Replace 0.55 0.15 by percent. 55% 15%

![image](https://github.com/user-attachments/assets/cc3ceea8-ae77-456a-9d7c-768f14eb1aa3)

**Comment by brunocalado** [comment]
Replace 0.55 0.15 by percent. 55% 15%
Only appers on the example created. It don't happen on new soundscapes

**Comment by mrcomac** [comment]
This should be available in V0.1.2
