### ISSUE TITLE
Adding Text Formatting to Imported Sound Names

### ISSUE THREAD

**Issue by brunocalado** [piecesofcodecom/soundscape-adventure#9]
Hi. Could you add some text formatting to the names of imported sounds? Examples: 
1. Spaces appear as spaces instead of HTML code.
2. Letters are capitalized.
3. Hyphens (-) and underscores (_) are replaced with spaces.
4. Extensions are removed along with the period.

So the sound "my-sound%20.mp3" would become "My Sound".

![image](https://github.com/user-attachments/assets/c47ff8ce-7d25-4dda-ab87-e26673cc7ae2)

**Comment by brunocalado** [comment]
I used something like that one time:
```
  static splitPath(str) {
    // Name Cleaning
    let imageName = str.split('\\').pop().split('/').pop(); // remove path
    imageName = imageName.split('.').slice(0, -1).join('.'); // remove extension
    imageName = imageName.replace(/_/g, " ");
    imageName = imageName.replace(/-/g, " ");
    return decodeURI( imageName );
  }
```

**Comment by mrcomac** [comment]
The new version allows edit the sound's name.
